server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/gunmarket
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
logging:
  level:
    io.gunmarket.demo: TRACE

---
spring:
  profiles:
    prod
  datasource:
    password: postgres
