name: CI

on:
  push:
    branches: 
    - master
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2.0.0
    - run: echo ${{matrix.os}}
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
